// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: wal/v1/wal.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Crc           uint32                 `protobuf:"varint,2,opt,name=crc,proto3" json:"crc,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_wal_v1_wal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_wal_v1_wal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_wal_v1_wal_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Record) GetCrc() uint32 {
	if x != nil {
		return x.Crc
	}
	return 0
}

func (x *Record) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_wal_v1_wal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_wal_v1_wal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_wal_v1_wal_proto_rawDescGZIP(), []int{1}
}

func (x *Entry) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Entry) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Entry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_wal_v1_wal_proto protoreflect.FileDescriptor

const file_wal_v1_wal_proto_rawDesc = "" +
	"\n" +
	"\x10wal/v1/wal.proto\x12\x06wal.v1\"B\n" +
	"\x06Record\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x10\n" +
	"\x03crc\x18\x02 \x01(\rR\x03crc\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"G\n" +
	"\x05Entry\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04dataB\aZ\x05./;v1b\x06proto3"

var (
	file_wal_v1_wal_proto_rawDescOnce sync.Once
	file_wal_v1_wal_proto_rawDescData []byte
)

func file_wal_v1_wal_proto_rawDescGZIP() []byte {
	file_wal_v1_wal_proto_rawDescOnce.Do(func() {
		file_wal_v1_wal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wal_v1_wal_proto_rawDesc), len(file_wal_v1_wal_proto_rawDesc)))
	})
	return file_wal_v1_wal_proto_rawDescData
}

var file_wal_v1_wal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wal_v1_wal_proto_goTypes = []any{
	(*Record)(nil), // 0: wal.v1.Record
	(*Entry)(nil),  // 1: wal.v1.Entry
}
var file_wal_v1_wal_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wal_v1_wal_proto_init() }
func file_wal_v1_wal_proto_init() {
	if File_wal_v1_wal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wal_v1_wal_proto_rawDesc), len(file_wal_v1_wal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wal_v1_wal_proto_goTypes,
		DependencyIndexes: file_wal_v1_wal_proto_depIdxs,
		MessageInfos:      file_wal_v1_wal_proto_msgTypes,
	}.Build()
	File_wal_v1_wal_proto = out.File
	file_wal_v1_wal_proto_goTypes = nil
	file_wal_v1_wal_proto_depIdxs = nil
}
